trigger:
  branches:
    include:
    - master
    - feature/ci-dev
  paths:
    exclude:
    - README.md
    - LICENSE
    - .travis.yml
    - book.toml
    - docker/*
    - manual/*
    - docs/*

jobs:
- job: Darwin
  timeoutInMinutes: 180
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      ./scripts/provision_mac.sh
      # speeds up provisioning
      export HOMEBREW_NO_AUTO_UPDATE=1
      # prepare environment for the following steps
      source $HOME/.cargo/env
      # print some useful info to help troubleshoot
      brew info llvm@17
      which python3
      /usr/bin/env python3 -c "import sys; print(sys.path)"
    displayName: 'Provision macOS'

  - script: |
      export LLVM_CONFIG_PATH=$(brew --prefix llvm@17)/bin/llvm-config
      export RUSTFLAGS="-D warnings"
      export RUSTDOCFLAGS="-D warnings"
      # Don't build with `--all-features` (see analogous step for Linux).
      cargo build --release
    displayName: 'cargo build against host clang/LLVM (fast build)'

  - script: |
      $(brew --prefix llvm@17)/bin/llvm-config
      export RUSTFLAGS="-D warnings"
      export RUSTDOCFLAGS="-D warnings"
      cargo test --release --workspace
    displayName: 'cargo test'

  - script: |
      # `RUSTFLAGS` not set (see analogous step for Linux).
      ./scripts/test_translator.py tests/
    displayName: 'Test translator (fast build)'
