[workspace]
members = [
    "c2rust",
    "c2rust-analyze",
    "c2rust-transpile",
    "c2rust-ast-builder",
    "c2rust-ast-exporter",
    "c2rust-ast-printer",
    "c2rust-bitfields",
    "c2rust-asm-casts",
    "analysis/runtime",
    "dynamic_instrumentation",
    "pdg",
    "c2rust-build-paths",
]
exclude = [
    "c2rust-macros",
    "examples",
    "analysis/tests",
    "tests",
]

[profile.dev.package."*"]
opt-level = 3
